### ISSUE TITLE
App crashes when leaving activity to a next activity

### ISSUE THREAD

**Issue by larrytech7** [tommybuonomo/squaresandcirclesloading#1]
I use the widget as a view in my splashscreen activity and when i start the next activity via an Intent, it stops. Well, my other activity starts quite alright, then fails a few seconds later. I have ran this on two versions of android lolipop, 5.0 and 5.1. The error points straight to a section lacking the NullPointer check which i believed can be easily and quickly patched.
Here is the log

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: domain.sub.pango, PID: 17942
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.AnimatorSet.start()' on a null object reference
                                                                       at com.tbuonomo.squaresandcirclesloading.SquaresAndCirclesLoadingView$4.onAnimationEnd(SquaresAndCirclesLoadingView.java:170)
                                                                       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
                                                                       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
                                                                       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:559)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by larrytech7** [comment]
I suggest initializing the circleAnimator at the beginning of the method (setUpAnimators) because i'm suspecting that when a listener is setup on the valueAnimator, it fires before the circleAnimator has been initialized.

**Comment by tommybuonomo** [comment]
Hi @larrytech7 !

Thank you for considering my library. You're right, there is a NullPointerException when changing activity. The reason is the `mCircleAnimator`'s child animators wasn't ended in the `onDetachedFromWindow()` method.

Thank you again for reaching out!
